### ISSUE TITLE
ULA or ULS sensor?

### ISSUE THREAD

**Issue by JeroenvIS** [mathias-buder/water-level-measure#1]
Hi, I came across this project through your Tasmota contribution. I'm trying a bit of tank and tube water level monitoring, so this looks interesting.

One detail though: in this project, you refer to the sensor as "ME007-ULA", while the commits in Tasmota mention "ME007-ULS". From what I see, it appears that these two models have a slightly different electrical interface.

Can you share which is the correct model for your project? And do you have a link where you bought the sensor? Thanks in advance!

**Comment by mathias-buder** [comment]
Hi Jeroen, good catch. I'm actually using ME007-ULS which I bought at [dfrobot](https://www.dfrobot.com/product-1889.html). For some reason you won't fine it when you search for ME007-ULS, you need to use their P/N: SEN0300.

The driver only support ME007-ULS's serial output mode at the moment. See https://wiki.dfrobot.com/Water-proof%20Ultrasonic%20Sensor%20(ULS)%20%20SKU:%20SEN0300 for details.
